using System.IO;
using System.Linq;
using SwarmUI.Core;
using SwarmUI.Utils;
using SwarmUI.Text2Image;
using SwarmUI.Builtin_ComfyUIBackend;
using Newtonsoft.Json.Linq;

namespace VideoConcat;

public class VideoConcatExtension : Extension
{
    public static T2IParamGroup VideoConcatGroup;

    public static T2IRegisteredParam<string> VideoConcatSectionPrompts;
    public static T2IRegisteredParam<string> VideoConcatSectionDurations;
    public static T2IRegisteredParam<int> VideoConcatTransitionFrames;
    public static T2IRegisteredParam<bool> VideoConcatEnableColorMatch;
    public static T2IRegisteredParam<double> VideoConcatColorStrength;
    public static T2IRegisteredParam<bool> VideoConcatEnableTemporalBlend;
    public static T2IRegisteredParam<double> VideoConcatTemporalStrength;

    public override void OnPreInit()
    {
        ScriptFiles.Add("assets/video-concat.js");
        StyleSheetFiles.Add("assets/video-concat.css");
    }

    public override void OnInit()
    {
        Logs.Init("VideoConcat Extension initializing...");

        RegisterParameters();
        RegisterComfyNodes();
        RegisterWorkflowStep();
    }

    private void RegisterComfyNodes()
    {
        string rootPath = string.IsNullOrWhiteSpace(FilePath) ? "src/Extensions/VideoConcat" : FilePath;
        string nodeFolder = Path.GetFullPath(Path.Join(rootPath, "comfy_node"));
        if (!Directory.Exists(nodeFolder))
        {
            return;
        }
        if (ComfyUISelfStartBackend.CustomNodePaths.Contains(nodeFolder))
        {
            return;
        }

        ComfyUISelfStartBackend.CustomNodePaths.Add(nodeFolder);
        Logs.Init($"VideoConcat: added {nodeFolder} to ComfyUI CustomNodePaths");
    }

    private static void RegisterParameters()
    {
        VideoConcatGroup = new(
            Name: "Video Concatenation",
            Description: "Chain multiple video sections with temporal coherence.\n" +
                         "Each section continues from the last frames of the previous section.\n" +
                         "Requires a Video Model selected in 'Image To Video' group.\n" +
                         "The first video is generated by Image To Video with the main prompt.\n" +
                         "Enter prompts for subsequent videos separated by '|||'.\n" +
                         "Example: 'A cat running|||A cat jumping' for videos 2 and 3.",
            Toggles: true,
            Open: false,
            OrderPriority: 8,
            IsAdvanced: false
        );

        double priority = 0;

        VideoConcatSectionPrompts = T2IParamTypes.Register<string>(new T2IParamType(
            Name: "Section Prompts",
            Description: "Prompts for video sections 2 and beyond, separated by '|||'.\n" +
                         "The first video uses the main prompt from Image To Video.\n" +
                         "This parameter defines prompts for subsequent videos.\n" +
                         "Example: 'A cat running|||A cat jumping' generates:\n" +
                         "  - Video 1: main prompt (from Image To Video)\n" +
                         "  - Video 2: 'A cat running'\n" +
                         "  - Video 3: 'A cat jumping'",
            Default: "",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            ViewType: ParamViewType.PROMPT
        ));

        VideoConcatSectionDurations = T2IParamTypes.Register<string>(new T2IParamType(
            Name: "Section Durations",
            Description: "Duration in frames for each video section (including the first), separated by commas.\n" +
                         "Example: '25,30,25' for 3 sections.\n" +
                         "If empty, uses default Video Frames for all sections.\n" +
                         "If fewer durations than sections, remaining use default Video Frames.",
            Default: "",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatTransitionFrames = T2IParamTypes.Register<int>(new T2IParamType(
            Name: "Transition Frames",
            Description: "Number of frames to use for crossfade transitions between sections.\n" +
                         "More frames = smoother transition but longer generation.\n" +
                         "Recommended: 8-24 frames.",
            Default: "12",
            Min: 1,
            Max: 60,
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatEnableColorMatch = T2IParamTypes.Register<bool>(new T2IParamType(
            Name: "Enable Color Matching",
            Description: "Match colors between video sections for visual coherence.\n" +
                         "Uses histogram matching to align brightness and color distribution.",
            Default: "true",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatColorStrength = T2IParamTypes.Register<double>(new T2IParamType(
            Name: "Color Match Strength",
            Description: "How strongly to apply color matching between sections.\n" +
                         "1.0 = full match, 0.0 = no adjustment.",
            Default: "0.5",
            Min: 0,
            Max: 1,
            Step: 0.05,
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatEnableTemporalBlend = T2IParamTypes.Register<bool>(new T2IParamType(
            Name: "Enable Temporal Blending",
            Description: "Blend frames temporally to create smooth transitions.\n" +
                         "Reduces flickering and improves motion continuity between sections.",
            Default: "true",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatTemporalStrength = T2IParamTypes.Register<double>(new T2IParamType(
            Name: "Temporal Blend Strength",
            Description: "How strongly to apply temporal blending.\n" +
                         "1.0 = maximum smoothing, 0.0 = no temporal blending.",
            Default: "0.5",
            Min: 0,
            Max: 1,
            Step: 0.05,
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));
    }

    private static void RegisterWorkflowStep()
    {
        WorkflowGenerator.AddStep(g =>
        {
            string promptsRaw = g.UserInput.Get(VideoConcatSectionPrompts, "") ?? "";
            string[] sectionPrompts = promptsRaw.Split(["|||"], StringSplitOptions.RemoveEmptyEntries);
            
            if (sectionPrompts.Length == 0)
            {
                return;
            }

            if (!g.Features.Contains("video"))
            {
                throw new SwarmUserErrorException("Video concatenation requires video feature support");
            }

            if (!g.UserInput.TryGet(T2IParamTypes.VideoModel, out T2IModel videoModel) || videoModel == null)
            {
                throw new SwarmUserErrorException("Video concatenation requires a Video Model selected in 'Image To Video'");
            }

            string durationsRaw = g.UserInput.Get(VideoConcatSectionDurations, "") ?? "";
            int[] durations = ParseDurations(durationsRaw);
            
            int totalSections = sectionPrompts.Length + 1;
            
            if (durations.Length == 0)
            {
                int defaultFrames = g.UserInput.Get(T2IParamTypes.VideoFrames, 25, sectionId: T2IParamInput.SectionID_Video);
                durations = Enumerable.Repeat(defaultFrames, totalSections).ToArray();
            }
            else if (durations.Length < totalSections)
            {
                int defaultFrames = g.UserInput.Get(T2IParamTypes.VideoFrames, 25, sectionId: T2IParamInput.SectionID_Video);
                int missing = totalSections - durations.Length;
                durations = durations.Concat(Enumerable.Repeat(defaultFrames, missing)).ToArray();
            }

            int transitionFrames = g.UserInput.Get(VideoConcatTransitionFrames, 12);
            bool enableColorMatch = g.UserInput.Get(VideoConcatEnableColorMatch, true);
            double colorStrength = g.UserInput.Get(VideoConcatColorStrength, 0.5);
            bool enableTemporalBlend = g.UserInput.Get(VideoConcatEnableTemporalBlend, true);
            double temporalStrength = g.UserInput.Get(VideoConcatTemporalStrength, 0.5);

            try
            {
                JArray sections = new JArray();
                foreach (int duration in durations)
                {
                    sections.Add(new JObject { ["duration_frames"] = duration });
                }

                new VideoConcatenator(g)
                    .SetSections(sections, sectionPrompts)
                    .SetTransitionFrames(transitionFrames)
                    .SetColorMatching(enableColorMatch, colorStrength)
                    .SetTemporalBlending(enableTemporalBlend, temporalStrength)
                    .Concatenate();
            }
            catch (Exception ex)
            {
                Logs.Error($"VideoConcat extension error: {ex.Message}");
                throw new SwarmUserErrorException($"Failed to concatenate videos: {ex.Message}");
            }
        }, 11.5);
    }

    private static int[] ParseDurations(string durationsRaw)
    {
        string[] parts = durationsRaw.Split([',', ' ', '\t'], StringSplitOptions.RemoveEmptyEntries);
        List<int> durations = [];
        foreach (string part in parts)
        {
            if (int.TryParse(part.Trim(), out int duration) && duration > 0)
            {
                durations.Add(duration);
            }
        }
        return durations.ToArray();
    }
}