using System.IO;
using System.Linq;
using SwarmUI.Core;
using SwarmUI.Utils;
using SwarmUI.Text2Image;
using SwarmUI.Builtin_ComfyUIBackend;
using Newtonsoft.Json.Linq;

namespace VideoConcat;

public class VideoConcatExtension : Extension
{
    public static T2IParamGroup VideoConcatGroup;

    public static T2IRegisteredParam<string> VideoConcatSectionPrompts;
    public static T2IRegisteredParam<string> VideoConcatSectionDurations;
    public static T2IRegisteredParam<int> VideoConcatTransitionFrames;
    public static T2IRegisteredParam<string> VideoConcatTransitionMode;
    public static T2IRegisteredParam<string> VideoConcatFrameMode;
    public static T2IRegisteredParam<bool> VideoConcatEnableColorMatch;
    public static T2IRegisteredParam<double> VideoConcatColorStrength;
    public static T2IRegisteredParam<bool> VideoConcatEnableTemporalBlend;
    public static T2IRegisteredParam<double> VideoConcatTemporalStrength;
    public static T2IRegisteredParam<bool> VideoConcatEnableAudioFade;
    public static T2IRegisteredParam<int> VideoConcatAudioCrossfadeFrames;
    public static T2IRegisteredParam<T2IModel> VideoConcatExtensionModel;
    public static T2IRegisteredParam<bool> VideoConcatEnableRTXUpscale;

    public override void OnPreInit()
    {
        ScriptFiles.Add("assets/video-concat.js");
        StyleSheetFiles.Add("assets/video-concat.css");
    }

    public override void OnInit()
    {
        Logs.Init("VideoConcat Extension initializing...");

        RegisterParameters();
        RegisterComfyNodes();
        RegisterWorkflowStep();
    }

    private void RegisterComfyNodes()
    {
        string rootPath = string.IsNullOrWhiteSpace(FilePath) ? "src/Extensions/VideoConcat" : FilePath;
        string nodeFolder = Path.GetFullPath(Path.Join(rootPath, "comfy_node"));
        if (!Directory.Exists(nodeFolder))
        {
            return;
        }
        if (ComfyUISelfStartBackend.CustomNodePaths.Contains(nodeFolder))
        {
            return;
        }

        ComfyUISelfStartBackend.CustomNodePaths.Add(nodeFolder);
        Logs.Init($"VideoConcat: added {nodeFolder} to ComfyUI CustomNodePaths");
    }

    private static void RegisterParameters()
    {
        VideoConcatGroup = new(
            Name: "Video Concatenation",
            Description: "Chain multiple video sections with temporal coherence.\n" +
                         "Each section continues from the last frames of the previous section.\n" +
                         "Requires a Video Model selected in 'Image To Video' group.\n" +
                         "The first video is generated by Image To Video with the main prompt.\n" +
                         "Enter prompts for subsequent videos separated by '|||'.\n" +
                         "Example: 'A cat running|||A cat jumping' for videos 2 and 3.",
            Toggles: true,
            Open: false,
            OrderPriority: 8,
            IsAdvanced: false
        );

        double priority = 0;

        VideoConcatSectionPrompts = T2IParamTypes.Register<string>(new T2IParamType(
            Name: "Section Prompts",
            Description: "Prompts for video sections 2 and beyond, separated by '|||'.\n" +
                         "The first video uses the main prompt from Image To Video.\n" +
                         "This parameter defines prompts for subsequent videos.\n" +
                         "Example: 'A cat running|||A cat jumping' generates:\n" +
                         "  - Video 1: main prompt (from Image To Video)\n" +
                         "  - Video 2: 'A cat running'\n" +
                         "  - Video 3: 'A cat jumping'",
            Default: "",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            ViewType: ParamViewType.PROMPT
        ));

        VideoConcatSectionDurations = T2IParamTypes.Register<string>(new T2IParamType(
            Name: "Section Durations",
            Description: "Duration in frames for each video section (including the first), separated by commas.\n" +
                         "Example: '25,30,25' for 3 sections.\n" +
                         "If empty, uses default Video Frames for all sections.\n" +
                         "If fewer durations than sections, remaining use default Video Frames.",
            Default: "",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatTransitionFrames = T2IParamTypes.Register<int>(new T2IParamType(
            Name: "Transition Frames",
            Description: "Number of frames to use for crossfade transitions between sections.\n" +
                         "More frames = smoother transition but longer generation.\n" +
                         "Recommended: 8-24 frames.",
            Default: "12",
            Min: 1,
            Max: 60,
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatTransitionMode = T2IParamTypes.Register<string>(new T2IParamType(
            Name: "Transition Mode",
            Description: "How to blend between video sections.\n" +
                         "crossfade: Smooth blend between videos.\n" +
                         "fade_to_black: Fade out then fade in.\n" +
                         "fade_to_white: Fade to white then fade in.\n" +
                         "dissolve: Random pixel dissolve effect.",
            Default: "crossfade",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true,
            GetValues: _ => ["crossfade", "fade_to_black", "fade_to_white", "dissolve"]
        ));

        VideoConcatFrameMode = T2IParamTypes.Register<string>(new T2IParamType(
            Name: "Frame Mode",
            Description: "How to handle frames in transitions.\n" +
                         "include_overlap: Keep all frames, transition adds to total length.\n" +
                         "exclude_overlap: Remove overlap frames, same length as sections combined.\n" +
                         "Recommended: exclude_overlap for normal concatenation.",
            Default: "exclude_overlap",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true,
            GetValues: _ => ["include_overlap", "exclude_overlap"]
        ));

        VideoConcatEnableColorMatch = T2IParamTypes.Register<bool>(new T2IParamType(
            Name: "Enable Color Matching",
            Description: "Match colors between video sections for visual coherence.\n" +
                         "Uses histogram matching to align brightness and color distribution.",
            Default: "true",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatColorStrength = T2IParamTypes.Register<double>(new T2IParamType(
            Name: "Color Match Strength",
            Description: "How strongly to apply color matching between sections.\n" +
                         "1.0 = full match, 0.0 = no adjustment.",
            Default: "0.5",
            Min: 0,
            Max: 1,
            Step: 0.05,
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatEnableTemporalBlend = T2IParamTypes.Register<bool>(new T2IParamType(
            Name: "Enable Temporal Blending",
            Description: "Blend frames temporally to create smooth transitions.\n" +
                         "Reduces flickering and improves motion continuity between sections.",
            Default: "true",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatTemporalStrength = T2IParamTypes.Register<double>(new T2IParamType(
            Name: "Temporal Blend Strength",
            Description: "How strongly to apply temporal blending.\n" +
                         "1.0 = maximum smoothing, 0.0 = no temporal blending.",
            Default: "0.5",
            Min: 0,
            Max: 1,
            Step: 0.05,
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatEnableAudioFade = T2IParamTypes.Register<bool>(new T2IParamType(
            Name: "Enable Audio Crossfade",
            Description: "Crossfade audio between video sections for smooth transitions.\n" +
                         "Mixes audio during transitions just like video crossfade.",
            Default: "true",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));

        VideoConcatAudioCrossfadeFrames = T2IParamTypes.Register<int>(new T2IParamType(
            Name: "Audio Crossfade Frames",
            Description: "Number of VIDEO FRAMES for audio crossfade (converted to audio samples automatically).\n" +
                         "The audio crossfade duration will match this many video frames.\n" +
                         "Recommended: Match Transition Frames for sync, or use lower for quicker audio transitions.",
            Default: "8",
            Min: 1,
            Max: 60,
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true,
            DependNonDefault: VideoConcatEnableAudioFade.Type.ID
        ));

        VideoConcatExtensionModel = T2IParamTypes.Register<T2IModel>(new T2IParamType(
            Name: "Extension Model",
            Description: "Video model used to continue video sections beyond the first.\n" +
                         "REQUIRED when using Text2Video models (Mochi, pure Text2Video) as main model.\n" +
                         "Should be an Image2Video capable model (Wan I2V, SVD, LTXV, Hunyuan I2V, Cosmos).\n" +
                         "Can be the same model as your main model if it supports Image2Video.",
            Default: "",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true,
            GetValues: s => T2IParamTypes.CleanModelList(Program.MainSDModels.ListModelsFor(s)
                .Where(m => m.ModelClass is not null)
                .Select(m => m.Name))
        ));

        VideoConcatEnableRTXUpscale = T2IParamTypes.Register<bool>(new T2IParamType(
            Name: "Enable RTX Upscale",
            Description: "Apply NVIDIA RTX Video Super Resolution upscaling (2x) to the final video.\n" +
                         "Uses NVIDIA RTX VSR with ULTRA quality settings.\n" +
                         "WARNING: This is computationally expensive and will significantly increase generation time.\n" +
                         "Recommended for final output only, not previews.",
            Default: "false",
            Group: VideoConcatGroup,
            OrderPriority: priority++,
            FeatureFlag: "video",
            DoNotPreview: true
        ));
    }

    private static void RegisterWorkflowStep()
    {
        WorkflowGenerator.AddStep(g =>
        {
            string promptsRaw = g.UserInput.Get(VideoConcatSectionPrompts, "") ?? "";
            string[] sectionPrompts = promptsRaw.Split(["|||"], StringSplitOptions.RemoveEmptyEntries);
            
            if (sectionPrompts.Length == 0)
            {
                return;
            }

            if (!g.Features.Contains("video"))
            {
                throw new SwarmUserErrorException("Video concatenation requires video feature support");
            }

            // Check for Text2Video mode (main model is video, no VideoModel selected)
            T2IModel mainModel = g.UserInput.Get(T2IParamTypes.Model, null);
            T2IModel videoModel = g.UserInput.Get(T2IParamTypes.VideoModel, null);
            T2IModel extensionModel = g.UserInput.Get(VideoConcatExtensionModel, null);
            
            bool isText2Video = videoModel == null 
                && mainModel != null 
                && mainModel.ModelClass?.CompatClass?.IsText2Video == true;
            
            // Determine the model to use for continuations
            T2IModel continuationModel = extensionModel ?? videoModel;
            
            if (continuationModel == null)
            {
                if (isText2Video)
                {
                    throw new SwarmUserErrorException(
                        "Video Concatenation with Text2Video requires an 'Extension Model' " +
                        "in the Video Concatenation group. Please select a video model there."
                    );
                }
                else
                {
                    throw new SwarmUserErrorException(
                        "Video concatenation requires a Video Model selected in 'Image To Video', " +
                        "or an 'Extension Model' in the Video Concatenation group."
                    );
                }
            }

            string durationsRaw = g.UserInput.Get(VideoConcatSectionDurations, "") ?? "";
            // If no durations specified, don't set them - let VideoConcatenator read from the actual video
            int[] durations = ParseDurations(durationsRaw);

            int totalSections = sectionPrompts.Length + 1;

            if (durations.Length == 0)
            {
                // Don't fill in defaults here - let VideoConcatenator use the actual generated video's frame count
                durations = [];
            }
            else if (durations.Length < totalSections)
            {
                // Partial durations provided - still let VideoConcatenator fill the rest from actual video
                // We'll pass what we have and let it handle the rest
            }

            int transitionFrames = g.UserInput.Get(VideoConcatTransitionFrames, 12);
            string transitionMode = g.UserInput.Get(VideoConcatTransitionMode, "crossfade");
            string frameMode = g.UserInput.Get(VideoConcatFrameMode, "exclude_overlap");
            bool enableColorMatch = g.UserInput.Get(VideoConcatEnableColorMatch, true);
            double colorStrength = g.UserInput.Get(VideoConcatColorStrength, 0.5);
            bool enableTemporalBlend = g.UserInput.Get(VideoConcatEnableTemporalBlend, true);
            double temporalStrength = g.UserInput.Get(VideoConcatTemporalStrength, 0.5);
            bool enableAudioCrossfade = g.UserInput.Get(VideoConcatEnableAudioFade, true);
            int audioCrossfadeFrames = g.UserInput.Get(VideoConcatAudioCrossfadeFrames, 8);
            bool enableRTXUpscale = g.UserInput.Get(VideoConcatEnableRTXUpscale, false);

            try
            {
                JArray sections = new JArray();
                foreach (int duration in durations)
                {
                    sections.Add(new JObject { ["duration_frames"] = duration });
                }

                new VideoConcatenator(g)
                    .SetSections(sections, sectionPrompts)
                    .SetTransitionFrames(transitionFrames)
                    .SetTransitionMode(transitionMode)
                    .SetFrameMode(frameMode)
                    .SetColorMatching(enableColorMatch, colorStrength)
                    .SetTemporalBlending(enableTemporalBlend, temporalStrength)
                    .SetAudioCrossfade(enableAudioCrossfade, audioCrossfadeFrames)
                    .SetRTXUpscale(enableRTXUpscale)
                    .Concatenate();
            }
            catch (Exception ex)
            {
                Logs.Error($"VideoConcat extension error: {ex.Message}");
                throw new SwarmUserErrorException($"Failed to concatenate videos: {ex.Message}");
            }
        }, 11.5);
    }

    private static int[] ParseDurations(string durationsRaw)
    {
        string[] parts = durationsRaw.Split([',', ' ', '\t'], StringSplitOptions.RemoveEmptyEntries);
        List<int> durations = [];
        foreach (string part in parts)
        {
            if (int.TryParse(part.Trim(), out int duration) && duration > 0)
            {
                durations.Add(duration);
            }
        }
        return durations.ToArray();
    }
}